version: '2'
services:
  jekyll:
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --force_polling --watch --config  _config_dev.yml --incremental
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000