version: '2'
services:
  jekyll:
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --watch --config  _config_dev.yml --incremental --force_polling --verbose
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000